[package]
name = "DSLR"
version = "0.1.0"
authors = ["McM1k <gboudrie@student.42.fr>"]
edition = "2018"

[dependencies]
csv = "1.1.1"
plotlib = "0.4.0"
chrono = "0.4.9"
#structopt = "0.2.16"
#clap = { version = "2.33", default-features = false }
clap = "2.33.0"