[package]
name = "DSLR"
version = "0.1.0"
authors = ["McM1k <gboudrie@student.42.fr>"]
edition = "2018"

[dependencies]
csv = "1.1.1"
plotlib = "0.4.0"
chrono = "0.4.9"
clap = "2.33.0"
strum = "0.16.0"
strum_macros = "0.16.0"
pyo3 = "0.8.0"